### ISSUE TITLE
Todo 추가시 리스트 불러오기 및 입력창 비우기

### ISSUE THREAD

**Issue by hyunju1219** [younghee05/ToyProject_TodoList#19]
## 어떤 기능인가요?

> Todo Add Click 시 리스트 바로 불러오기 그 후 입력창 비우기, 날짜선택해서 추가하기

## 작업상세내용

- [x] 리스트 불러오는 기능 추가
- [x] 입력창 비우기 기능 추가
- [x] 날짜 선택 기능 추가
